name: Rust

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Build
        run: cargo build --release
      - name: Semantic Releaser
        uses: brpaz/action-semantic-release@v1
