name: Rust

on:
  workflow_dispatch:
  push:
    branches: ["sg108e"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Build
        run: cargo build --release
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: check_tl_sg108e
          path: target/release/check_tl_sg108e
